"""
Tests for ``CsvBuildingSource`` and ``geometry_utils`` (WKB point decoding
+ RD-New -> WGS84 reprojection), built for the real Netherlands/Loenen
data under ``src/buem/data/buildings/netherlands/Loenen/``.

**Data provenance changed 2026-08-16**: this data was originally a
city2tabula-derived CSV export, which turned out to carry two independent,
compounding duplicate-geometry bugs (see ``.claude/residential/
resolved.md``'s "Netherlands (Loenen) building data" entry for the full
story). It has since been **replaced entirely** with a clean, single-pass
extraction straight from the real CityJSON (3D BAG) source
(``buem.buildings.datasources.cityjson_extractor`` -- see that module's
own docstring for the extraction/party-wall/storeys methodology). The old
city2tabula CSVs are kept for reference under
``src/buem/data/buildings/netherlands/Loenen/_city2tabula_backup/`` but are no
longer read by anything. Building IDs are a fresh sequential scheme
(``cityjson_extractor`` assigns them in sorted-BAG-pand-id order) --
**not** the old city2tabula ``building_feature_id`` values referenced in
earlier commits/docs (e.g. "building 37206" no longer exists; the same
physical building is now identified by its stable ``bag_pand_id``, looked
up below rather than hardcoded).

**TABULA archetype matching landed 2026-08-17**
(``buem.buildings.datasources.nl_archetype_mapper`` -- see its module
docstring for the full methodology: real construction year/geometry-
derived building type, a real energy label as an override where present,
matched against the real bundled Dutch TABULA sheet). Almost every
building now has a real ``tabula_variant_code_id`` -- the ~4/3,105
flagged non-residential (greenhouse/warehouse/glasshouse) are the
deliberate exception. ``LOD2Mapper.map_building()`` succeeds end-to-end
for the vast majority of buildings in this dataset as of that date.

Gated the same way ``test_live_synthesis.py`` gates on the bundled
German workbook: these files are real data, not fixtures generated by
this repo, and may not be present in every environment (fresh checkout,
CI). Skip cleanly rather than fail when absent.
"""
from __future__ import annotations

import pytest

from buem.buildings.datasources.csv_source import CsvBuildingSource
from buem.buildings.mapping.geometry_utils import building_lat_lon, wkb_point_to_lat_lon

NL_DATA_DIR = "src/buem/data/buildings/netherlands/Loenen"

# A real building, independently ground-truthed against CityJSON during
# the 2026-08-16 investigation (4 walls/80.48 m2, 1 roof/39.84 m2, 1
# floor/39.43 m2, single storey, built 1907) -- looked up by its stable
# BAG identifier rather than a hardcoded (and now-changed) numeric id.
# Geometry-only fixture: used exclusively where the assertion is about
# raw extracted geometry, never residential classification -- this
# building's own small footprint means it is itself one of the
# no-registered-dwelling-unit exclusions issue #15 fixed (2026-08-21),
# so LOD2Mapper.map_building() now correctly returns None for it.
_KNOWN_BAG_PAND_ID = "NL.IMBAG.Pand.0200100000938969"

# A separate real building for classification-dependent (LOD2Mapper /
# U-value-override) tests, which need a Pand that is still classified
# residential after issue #15's fix: SFH/B_Alone/NL.01, real 98.2 m2
# floor area across 3 storeys, built 1931, a real matched TABULA
# archetype -- unambiguously a real house, not an outbuilding.
_KNOWN_RESIDENTIAL_BAG_PAND_ID = "NL.IMBAG.Pand.0200100000021015"

_nl_data_missing_reason = None
try:
    _source = CsvBuildingSource(NL_DATA_DIR)
except FileNotFoundError as exc:
    _source = None
    _nl_data_missing_reason = str(exc)

requires_nl_data = pytest.mark.skipif(
    _source is None, reason=_nl_data_missing_reason or "",
)


# ── geometry_utils: pure decoding, no I/O ────────────────────────────────


def test_wkb_point_to_lat_lon_known_coordinate():
    """A real hex WKB point from the original city2tabula Loenen export,
    hand-verified against its expected RD-New raw coordinates
    (197639.15, 461826.02) before this module existed. Pure decode test --
    independent of which building dataset is currently loaded."""
    hex_wkb = "010100002040710000DE22EC3639200841F10E781208301C41"
    lat, lon = wkb_point_to_lat_lon(hex_wkb)
    # Loenen, Gelderland, NL -- roughly 52.14N, 6.01E
    assert 52.0 < lat < 52.3
    assert 5.9 < lon < 6.1


def test_wkb_point_to_lat_lon_rejects_non_point():
    # A MultiPolygon Z EWKB header (type 6, with SRID+Z flags) -- not a
    # POINT, must raise rather than silently misinterpret the bytes.
    fake_multipolygon_header = "01060000A040710000" + "00" * 8
    with pytest.raises(ValueError, match="expected a POINT"):
        wkb_point_to_lat_lon(fake_multipolygon_header)


def test_building_lat_lon_returns_none_for_missing_geometry():
    import pandas as pd

    row = pd.Series({"building_centroid_geom": None})
    assert building_lat_lon(row) is None

    row_nan = pd.Series({"building_centroid_geom": float("nan")})
    assert building_lat_lon(row_nan) is None


def test_building_lat_lon_returns_none_and_warns_on_malformed_geometry(caplog):
    import pandas as pd

    row = pd.Series({"building_centroid_geom": "not-valid-hex"})
    with caplog.at_level("WARNING"):
        result = building_lat_lon(row)
    assert result is None


def test_region_center_lat_lon_averages_only_decodable_rows():
    """A row without geometry must be skipped, not counted as (0, 0) --
    which would drag the region's shared weather fetch into the Atlantic."""
    import pandas as pd

    from buem.buildings.mapping.geometry_utils import region_center_lat_lon

    hex_wkb = "010100002040710000DE22EC3639200841F10E781208301C41"
    expected_lat, expected_lon = wkb_point_to_lat_lon(hex_wkb)
    df = pd.DataFrame({"building_centroid_geom": [hex_wkb, None, hex_wkb]})

    lat, lon = region_center_lat_lon(df)

    assert lat == pytest.approx(expected_lat)
    assert lon == pytest.approx(expected_lon)


def test_region_center_lat_lon_raises_when_no_geometry_at_all():
    """Falling back to a module-default location here would simulate a
    region against another country's climate."""
    import pandas as pd

    from buem.buildings.mapping.geometry_utils import region_center_lat_lon

    with pytest.raises(ValueError, match="no building.*real geometry|No building"):
        region_center_lat_lon(pd.DataFrame({"building_centroid_geom": [None, None]}))


# ── CsvBuildingSource: real Netherlands/Loenen data ──────────────────────


@requires_nl_data
def test_csv_building_source_loads_expected_shape():
    source = CsvBuildingSource(NL_DATA_DIR)
    assert len(source.buildings) > 1000
    assert len(source.surfaces) > 10000
    assert len(source.tabula) > 0
    assert (source.tabula["Code_Country"] == "NL").all()


@requires_nl_data
def test_csv_building_source_id_columns_are_integer_dtype():
    source = CsvBuildingSource(NL_DATA_DIR)
    assert str(source.buildings["building_feature_id"].dtype) == "Int64"
    assert str(source.surfaces["building_feature_id"].dtype) == "Int64"
    assert str(source.surfaces["surface_feature_id"].dtype) == "Int64"


def test_csv_building_source_null_literal_parsed_as_nan(tmp_path):
    """Regression guard: a Postgres/pgAdmin CSV export's literal "NULL"
    text must not survive as the string "NULL" -- it has to become real
    NaN, or downstream float()/int() conversions elsewhere in the
    pipeline would break on it. This was a real quirk of the original
    city2tabula export (see module docstring); the current bundled
    dataset no longer exercises it (its own construction_year is fully
    populated from real BAG data), so this test now builds a tiny
    synthetic fixture directly -- decoupled from whatever the bundled
    data happens to contain, and still a real guard on the
    ``na_values=["NULL"]`` behavior itself."""
    (tmp_path / "lod2_building_feature.csv").write_text(
        "building_feature_id,tabula_variant_code_id,construction_year\n"
        "1,10,1990\n"
        "2,NULL,NULL\n",
        encoding="utf-8",
    )
    (tmp_path / "lod2_child_feature_surface.csv").write_text(
        "id,building_feature_id,surface_feature_id,objectclass_id,classname,surface_area\n"
        "a,1,1,710,GroundSurface,50.0\n",
        encoding="utf-8",
    )
    (tmp_path / "tabula.csv").write_text("id,Code_Country\n10,NL\n", encoding="utf-8")

    source = CsvBuildingSource(tmp_path)
    assert source.buildings["construction_year"].isna().any()
    non_na = source.buildings["construction_year"].dropna()
    assert not (non_na.astype(str) == "NULL").any()
    # tabula_variant_code_id=NULL must become real <NA>, not the string "NULL"
    assert source.buildings["tabula_variant_code_id"].isna().any()


@requires_nl_data
def test_csv_building_source_get_surfaces_for_building_matches_real_building():
    source = CsvBuildingSource(NL_DATA_DIR)
    ids = source.get_building_ids(limit=5)
    assert len(ids) == 5
    surfaces = source.get_surfaces_for_building(int(ids[0]))
    assert len(surfaces) > 0
    assert (surfaces["building_feature_id"] == ids[0]).all()


@requires_nl_data
def test_csv_building_source_get_tabula_row_resolves_real_archetype():
    """The TABULA reference table itself (unaffected by the CityJSON
    regeneration -- it's real Dutch typology data, not Loenen-geometry-
    derived) still resolves normally when given a real id directly."""
    source = CsvBuildingSource(NL_DATA_DIR)
    real_tabula_id = source.tabula["id"].iloc[0]
    tabula_row = source.get_tabula_row(real_tabula_id)
    assert tabula_row is not None
    assert tabula_row["Code_Country"] == "NL"


@requires_nl_data
def test_csv_building_source_most_buildings_have_a_tabula_match():
    """The real residential population is ~1,335 of 3,105 raw Pand
    records, and virtually all of it gets a TABULA match. The other
    ~1,770 are correctly left unmatched rather than being a regression,
    for two distinct reasons:

    - Pands with no RIVM-registered dwelling unit -- garden sheds,
      garages, farm outbuildings (``nl_building_classifier``'s
      registration-status exclusion).
    - Pands whose registered BAG use function is entirely
      non-residential -- shops, offices, schools, industry. These are
      real occupied buildings, but they belong to the service-building
      path (``service_building_type``) and TABULA, a residential
      typology, has no archetype for them.

    The bound tracks the residential population only, so it moves
    whenever either exclusion changes; both narrowed it deliberately."""
    source = CsvBuildingSource(NL_DATA_DIR)
    n_matched = source.buildings["tabula_variant_code_id"].notna().sum()
    assert 1250 < n_matched < 1400
    bldg_row = source.buildings[source.buildings["tabula_variant_code_id"].notna()].iloc[0]
    tabula_row = source.get_tabula_row(bldg_row["tabula_variant_code_id"])
    assert tabula_row is not None
    assert tabula_row["Code_Country"] == "NL"


@requires_nl_data
def test_lod2mapper_maps_known_building_end_to_end():
    """Full pipeline for a real, unambiguously-residential building (see
    _KNOWN_RESIDENTIAL_BAG_PAND_ID): real TABULA match, real (not
    default 52.0/5.0) lat/lon, and windows/doors/ventilation actually
    synthesized now that a real archetype exists (previously blocked
    entirely -- see
    test_lod2mapper_returns_none_pending_tabula_archetype_mapping's
    2026-08-16 note, now removed since this is exactly what it was
    watching for)."""
    from buem.buildings.mapping.lod2_mapper import LOD2Mapper

    source = CsvBuildingSource(NL_DATA_DIR)
    mapper = LOD2Mapper(source, country="NL")
    match = source.buildings[source.buildings["bag_pand_id"] == _KNOWN_RESIDENTIAL_BAG_PAND_ID].iloc[0]
    bldg = mapper.map_building(int(match["building_feature_id"]))

    assert bldg is not None
    assert bldg.identity.building_type == "SFH"
    assert bldg.identity.neighbour_status == "B_Alone"
    # real Loenen coordinates, not BuildingIdentity's class default
    assert (bldg.identity.latitude, bldg.identity.longitude) != (52.0, 5.0)
    assert 52.0 < bldg.identity.latitude < 52.3
    assert 5.9 < bldg.identity.longitude < 6.1

    element_types = [e.element_type for e in bldg.elements]
    assert "window" in element_types
    assert "door" in element_types
    assert "ventilation" in element_types


@requires_nl_data
def test_lod2mapper_applies_u_value_overrides():
    """The editable envelope reference table actually takes effect -- not
    just documentation. A building matched to NL.01/SFH must use that
    row's U-values, not whatever the raw TABULA archetype row's own
    U_Wall_1/etc. happen to be (they're equal here by construction, see
    nl_envelope_reference.csv's own provenance, but this test would catch
    a wiring regression that silently stopped applying the override).

    Resolves the table the same way the runners do, so it follows the
    packaged national file, a region-local override, or an explicit path
    without needing to know which is in play."""
    from buem.buildings.mapping.lod2_mapper import LOD2Mapper
    from buem.config.reference_values import resolve_envelope_reference

    overrides = resolve_envelope_reference(None, NL_DATA_DIR, country="NL")
    assert overrides is not None, "no envelope reference resolved for NL"
    source = CsvBuildingSource(NL_DATA_DIR)
    mapper = LOD2Mapper(source, country="NL", u_value_overrides=overrides)
    match = source.buildings[source.buildings["bag_pand_id"] == _KNOWN_RESIDENTIAL_BAG_PAND_ID].iloc[0]
    bldg = mapper.map_building(int(match["building_feature_id"]))

    assert bldg is not None
    expected = overrides[
        (overrides["construction_year_class"] == "NL.01") & (overrides["building_type"] == "SFH")
    ].iloc[0]
    walls = [e for e in bldg.elements if e.element_type == "wall"]
    roofs = [e for e in bldg.elements if e.element_type == "roof"]
    assert all(w.U == pytest.approx(expected["U_Wall"]) for w in walls)
    assert roofs[0].U == pytest.approx(expected["U_Roof"])


@requires_nl_data
def test_building_lat_lon_decodes_real_loenen_buildings():
    source = CsvBuildingSource(NL_DATA_DIR)
    for _, row in source.buildings.head(50).iterrows():
        result = building_lat_lon(row)
        assert result is not None, f"building {row['building_feature_id']} failed to decode"
        lat, lon = result
        # Loenen, Gelderland is roughly 52.0-52.3N, 5.8-6.2E -- sanity
        # bound, not a tight assertion (real buildings scattered locally).
        assert 51.5 < lat < 53.0
        assert 5.0 < lon < 7.0


# ── clean CityJSON regeneration: verification guards (2026-08-16) ────────
#
# The original city2tabula CSV export carried two independent,
# compounding duplicate-geometry bugs (see .claude/residential/
# resolved.md's "Netherlands (Loenen) building data" entry: an exact-
# duplicate-row layer, fixed first in CsvBuildingSource; and a second
# "near-identical batch" layer found while cross-checking that fix
# against real CityJSON ground truth, never safely fixable from the
# export alone). Both are now moot: the dataset was regenerated from
# scratch, directly from CityJSON, via
# buem.buildings.datasources.cityjson_extractor -- see its own docstring
# for the full methodology (party-wall geometric coincidence detection,
# storeys estimation, etc.). CsvBuildingSource's dedup/aggregate-recompute
# logic (added for the city2tabula export) still runs over this data too,
# but is now a no-op by construction -- there is nothing left to dedupe.
# These tests confirm exactly that, plus the regenerated numbers for one
# building independently ground-truthed against CityJSON during the same
# investigation.


@requires_nl_data
def test_csv_building_source_no_exact_duplicates_dataset_wide():
    """No (building_feature_id, surface_feature_id, classname, surface_area,
    tilt, azimuth, height, is_valid, is_planar) combination should appear
    more than once anywhere in the loaded surfaces table -- true by
    construction for the CityJSON-derived data (one row per real face,
    no fragmentation/duplication step exists), unlike the old city2tabula
    export."""
    source = CsvBuildingSource(NL_DATA_DIR)
    key_cols = [c for c in source.surfaces.columns if c not in ("id", "child_row_id")]
    assert not source.surfaces.duplicated(subset=key_cols).any()


@requires_nl_data
def test_csv_building_source_matches_cityjson_ground_truth_for_known_building():
    """The known building (see _KNOWN_BAG_PAND_ID) reproduces exactly the
    numbers independently computed straight from CityJSON during the
    2026-08-16 investigation: 4 walls/80.48 m2, 1 roof/39.84 m2, 1
    floor/39.43 m2, built 1907, single storey."""
    source = CsvBuildingSource(NL_DATA_DIR)
    match = source.buildings[source.buildings["bag_pand_id"] == _KNOWN_BAG_PAND_ID]
    assert len(match) == 1
    brow = match.iloc[0]
    bid = int(brow["building_feature_id"])
    surfaces = source.get_surfaces_for_building(bid)

    by_class = surfaces["classname"].value_counts().to_dict()
    assert by_class == {"WallSurface": 4, "RoofSurface": 1, "GroundSurface": 1}

    assert brow["area_total_wall"] == pytest.approx(80.48443, abs=1e-3)
    assert brow["area_total_roof"] == pytest.approx(39.83981, abs=1e-3)
    assert brow["area_total_floor"] == pytest.approx(39.43053, abs=1e-3)
    assert int(brow["number_of_storeys"]) == 1
    assert int(brow["construction_year"]) == 1907
    # geometry-derived aggregates must match a fresh sum over the surfaces
    # themselves too (CsvBuildingSource's recompute step, now a no-op here)
    wall_area = surfaces.loc[surfaces["classname"] == "WallSurface", "surface_area"].sum()
    assert brow["area_total_wall"] == pytest.approx(wall_area)
